"""fix project relationship

Revision ID: 3d0a7ba508d1
Revises: c21f826c77a5
Create Date: 2026-02-15 10:25:10.368182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d0a7ba508d1'
down_revision: Union[str, Sequence[str], None] = 'c21f826c77a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa


def upgrade():
    # 1️⃣ Add column nullable first
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # 2️⃣ Fill existing rows
    op.execute("UPDATE projects SET is_deleted = FALSE WHERE is_deleted IS NULL")

    # 3️⃣ Make NOT NULL
    op.alter_column('projects', 'is_deleted', nullable=False)

    # share_id column
    op.add_column('projects', sa.Column('share_id', sa.UUID(), nullable=True))
    op.create_index('ix_projects_share_id', 'projects', ['share_id'], unique=True)


def downgrade():
    op.drop_index('ix_projects_share_id', table_name='projects')
    op.drop_column('projects', 'share_id')
    op.drop_column('projects', 'is_deleted')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_share_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_column('projects', 'share_id')
    op.drop_column('projects', 'is_deleted')
    op.create_table('project_collaborators',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'viewer'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_collaborators_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_collaborators_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_collaborators_pkey')),
    sa.UniqueConstraint('project_id', 'user_id', name=op.f('uq_project_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
